### ISSUE TITLE
구현 기술 선택

### ISSUE THREAD

**Issue by spckce** [spckce/SPChat#1]

**Comment by pshsh88** [comment]
방향성
1. 앱 기반
  - 확인 필요
2. 웹 기반
  - WebRTC 기술 기반 > 나도 잘 모름 찾아봐야 함 ㅋㅋ
    https://github.com/spckce/SPChat/wiki/SPChat-%EA%B0%9C%EB%B0%9C-%EC%A7%84%ED%96%89-Wiki 에 참고 링크 걸어둠

**Comment by pshsh88** [comment]
WebRTC 기반 & Javascript 로 하는 것으로 땅땅!

**Comment by oddheo** [comment]
javascript ES6(?) 을 쓸 것인가????

**Comment by pso1027** [comment]
브라우저들이 ES6 지원한지는 좀된거같아서 난 ES6 쓰는게 좋을거같음

**Comment by pshsh88** [comment]
ES6가 러닝커브가 있지만 잘 사용하면 의외로 편리함. 그리고 브라우저 호환성 문제는 babel같은 라이브러리로 하위호환 가능한 모듈로 컨버팅도 해주니까 그런건 괜찮음. 
너네가 ES6 공부하는데 부담이 없다면 나도 ES6 한표. 근데 ES6라고 해서 아예 새로운건 아니고 결국에 대부분은 동일해서 괜찮을거야 ㅋㅋ 

ES6 공부할거면 이 링크로 하면 됨.
http://exploringjs.com/es6/index.html#toc_ch_first-steps

그럼 난 이만 퇴근

**Comment by oddheo** [comment]
ES6 를 합시다 땅땅땅
